# Generated by Django 4.0.4 on 2022-07-05 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('live_for_purpose', '0002_blog_delete_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.CharField(max_length=255)),
                ('mail_id', models.EmailField(max_length=254)),
                ('body', models.TextField()),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('comm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='live_for_purpose.blog')),
            ],
        ),
    ]
