# Generated by Django 4.0.4 on 2022-07-06 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('live_for_purpose', '0003_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='comm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='live_for_purpose.blog'),
        ),
    ]
