# Generated by Django 4.0.4 on 2022-07-06 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('live_for_purpose', '0004_alter_comments_comm'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='mail_id',
            new_name='Mail_id',
        ),
        migrations.RenameField(
            model_name='comments',
            old_name='body',
            new_name='Message',
        ),
        migrations.RenameField(
            model_name='comments',
            old_name='person',
            new_name='Name',
        ),
        migrations.AlterField(
            model_name='comments',
            name='comm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='live_for_purpose.blog'),
        ),
    ]
