# Generated by Django 4.0.4 on 2022-07-06 18:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('live_for_purpose', '0005_rename_mail_id_comments_mail_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='')),
                ('body', models.TextField()),
                ('descript', models.TextField()),
                ('auth_detail', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='comments',
            name='comm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='live_for_purpose.post'),
        ),
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
